# Set memory used for Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.configuration-cache=true

# Minecraft properties
java_version = 21
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
parchment_version=2024.11.17

# Mod properties
mod_id=skyislands
mod_name=Sky's Sky Islands
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group=gay.beegirl.skyislands

# Dependencies
neo_version=21.1.230
loader_version_range=[1,)
pal_version=1.1.5+mc.1.21.1