org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.233
loader_version_range=[1,)

## Dependencies
sable_version=2.0.3
sable_companion_version=1.6.0

## Mod Properties
mod_id=skyislands
mod_name=Sky's Sky Islands
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=gay.beegirl.skyislands
